services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: rebelist-streamline-api
    ports:
      - "8000:8000"
    networks:
      - streamline
    restart: no
    env_file:
      - .env
    profiles: [ "prod" ]
    depends_on:
      - mongo
    volumes:
      - ./settings.ini:/home/streamline/app/settings.ini
      - ./.env.prod:/home/streamline/app/.env

  mongo:
    image: mongodb/mongodb-community-server:8.0.12-ubi9
    container_name: rebelist-streamline-mongo
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    profiles: [ ]
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo/mongod.conf:/etc/mongod.conf:ro
      - ./docker/mongo/mongosh.conf:/etc/mongosh.conf:ro
    networks:
      - streamline

  grafana:
    image: grafana/grafana:12.0.4
    container_name: rebelist-streamline-grafana
    ports:
      - "80:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_DISABLE_INITIAL_ADMIN_PASSWORD_CHANGE: true
      GF_AUTH_BASIC_ENABLED: false
      GF_DASHBOARDS_PROVIDERS_0_NAME: default
      GF_DASHBOARDS_PROVIDERS_0_ORG_ID: "1"
      GF_DASHBOARDS_PROVIDERS_0_FOLDER: /etc/grafana/datasources/dashboards
      GF_DASHBOARDS_PROVIDERS_0_TYPE: file
      GF_DASHBOARDS_PROVIDERS_0_DISABLE_SANDBOXING: "true" # Required for file-based dashboard datasources in some cases
      GF_DATASOURCES_PROVIDERS_0_NAME: default
      GF_DATASOURCES_PROVIDERS_0_ORG_ID: "1"
      GF_DATASOURCES_PROVIDERS_0_FOLDER: /etc/grafana/datasources/datasources
      GF_DATASOURCES_PROVIDERS_0_TYPE: file
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 5s
      timeout: 5s
      retries: 3
    profiles: [ ]
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - streamline

volumes:
  mongo_data:
  grafana_data:

networks:
  streamline:
    driver: bridge
