[app]
name = "Streamline"
version = "0.1.0"
region = "DE"

[team]
name = "Loki"
workday_starts_at = "8:00"
workday_ends_at = "18:00"
workday_duration = 8

[jira]
project = "HIVE"
board_id = 533
sprint_start_at = 35